name: build

on:
  push:
    branches:
      - main

jobs:
  build-others:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: bupt-net-login
            name: bupt-net-login_darwin-x86_64.tar.gz
            command: build

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: bupt-net-login
            name: bupt-net-login_darwin-aarch64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: bupt-net-login.exe
            name: bupt-net-login-windows-x86_64.zip
            command: build

          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: bupt-net-login
            name: bupt-net-login_linux-x86_64.tar.gz
            command: build

          - release_for: Linux-arm
            os: ubuntu-latest
            target: arm-unknown-linux-gnueabi
            bin: bupt-net-login
            name: bupt-net-login_linux-arm.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Copy binary for archive
        run: cp target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} .
      - name: Archive binary on Windows
        if: runner.os == 'Windows'
        run: Compress-Archive -Path ${{ matrix.platform.bin }} -DestinationPath ${{ matrix.platform.name }}
      - name: Archive binary on macOS and Linux
        if: runner.os != 'Windows'
        run: tar -czf ${{ matrix.platform.name }} ${{ matrix.platform.bin }}
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ matrix.platform.name }}
