name: build‑cpp

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - linux-arm64-musl
          - linux-mips-lts
          - linux-mipsel-lts
          - linux-s390x
          - linux-ppc64le-lts
          - linux-riscv32
          - linux-riscv64
          - linux-m68k-uclibc
          - linux-xtensa-uclibc
          - linux-x64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build ${{ matrix.arch }}
        run: |
          cd cpp
          docker run --rm \
            -v "$PWD":/work \
            dockcross/${{ matrix.arch }} \
            bash -lc "make"

      - name: Archive binary
        run: |
          mv cpp/bupt-net-login .
          tar -czf bupt-net-login_cpp-${{ matrix.arch }}.tar.gz bupt-net-login

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        if:
          github.event.action == 'published'
        with:
          files: bupt-net-login_cpp-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary to artifact
        if:
          github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: bupt-net-login_cpp-${{ matrix.arch }}
          path: bupt-net-login_cpp-${{ matrix.arch }}.tar.gz
